rts/config/routes.rb
Rts::Application.routes.draw do




  #get "/managers(.:format)" => "managers#index"
  #get "/api/managers/:hp" => "managers#show"
    #get "/managers(.:format)" => "managers#index"
  #put "/api/managers/:hp" => "managers#update"

  scope '/api' do

  resources :answers

  resources :paper_types, :id => /.*/

  resources :custom_groups

  resources :jobs

  resources :gifts

  resources :authorities

  resources :managers, :id => /.*/

  resources :customs

  resources :custom_answers

  resources :paper_histories

  resources :question_types

  resources :question_items

  resources :directives

  resources :papers

  resources :manager, :id => /.*/

  resources :groupinfos, :id => /.*/

  resources :shares

  #get "/manager/basicInfo" => 'manager#basicInfo'

    devise_for :users,
      :controllers => {
        omniauth_callbacks: "users/omniauth_callbacks",
        registrations: "users/registrations",
        sessions: "users/sessions"
      }

    devise_scope :user do
      post '/check/is_user' => 'users/users#is_user', as: 'is_user'
      post '/current_user' => 'users/sessions#get_current_user'
      
    end

  end


  get '/dashboard' => 'welcome#dashboard'
  root to: 'welcome#index'
end

rts/app/models/paper.rb
class Paper
  include Mongoid::Document
  #field :paper_id, type: String
  field :group_code, type: String
  field :user_id, type: String
  field :paper_type_code, type: String
  field :limit_time, type: Integer
  field :question_type, type: String
  field :is_automatic, type: String
  field :in_use, type: String

  auto_increment :paper_id

  belongs_to :groupinfo
  belongs_to :papertype
  belongs_to :manager
  
  # error ?
  #has_many :paperhistory 
  has_many :directive
  has_many :gift

end

rts/app/models/paper_type.rb
class PaperType
  include Mongoid::Document
  field :paper_type_code, type: String
  field :name, type: String
  field :user_id, type: String

  has_many :paper
  has_many :manager
end

rts/app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  respond_to json:
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    #respond_to do |format|
      if @paper.save
    #    format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
    #    format.json { render action: 'show', status: :created, location: @paper }
        render json: @paper
      else
    #    format.html { render action: 'new' }
    #    format.json { render json: @paper.errors, status: :unprocessable_entity }
        render json: @paper.errors, status: :unprocessable_entity
      end
    #end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
  #  respond_to do |format|
      if @paper.update(paper_params)
  #      format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
  #      format.json { head :no_content }
         render json: @paper
      else
  #      format.html { render action: 'edit' }
  #      format.json { render json: @paper.errors, status: :unprocessable_entity }
          render json: @paper.errors, status: :unprocessable_entity
      end
  #  end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy

    #respond_to do |format|
    #  format.html { redirect_to papers_url }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:paper_id, :group_code, :user_id, :paper_type_code, :limit_time, :question_type, :is_automatic, :in_use)
     # params.require(:paper).permit(:group_code, :user_id, :paper_type_code, :limit_time, :question_type, :is_automatic, :in_use)
    end
end

rts/app/helpers/papers_helper.rb
module PapersHelper
end

rts/app/views/papers/_form.html.slim
= form_for @paper do |f|
  - if @paper.errors.any?
    #error_explanation
      h2 = "#{pluralize(@paper.errors.count, "error")} prohibited this paper from being saved:"
      ul
        - @paper.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :paper_id
    = f.text_field :paper_id
  .field
    = f.label :group_code
    = f.text_field :group_code
  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :paper_type_code
    = f.text_field :paper_type_code
  .field
    = f.label :limit_time
    = f.number_field :limit_time
  .field
    = f.label :question_type
    = f.text_field :question_type
  .field
    = f.label :is_automatic
    = f.text_field :is_automatic
  .field
    = f.label :in_use
    = f.text_field :in_use
  .actions = f.submit 'Save'

rts/app/views/papers/edit.html.slim
h1 Editing paper

== render 'form'

= link_to 'Show', @paper
'|
= link_to 'Back', papers_path

rts/app/views/papers/index.html.slim
h1 Listing papers

table
  tr
    th Paper
    th Group code
    th User
    th Paper type code
    th Limit time
    th Question type
    th Is automatic
    th In use
    th
    th
    th

  - @papers.each do |paper|
    tr
      td = paper.paper_id
      td = paper.group_code
      td = paper.user_id
      td = paper.paper_type_code
      td = paper.limit_time
      td = paper.question_type
      td = paper.is_automatic
      td = paper.in_use
      td = link_to 'Show', paper
      td = link_to 'Edit', edit_paper_path(paper)
      td = link_to 'Destroy', paper, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Paper', new_paper_path

rts/app/views/papers/new.html.slim
h1 New paper

== render 'form'

= link_to 'Back', papers_path

rts/app/views/papers/show.html.slim
p#notice = notice

p
  strong Paper:
  = @paper.paper_id
p
  strong Group code:
  = @paper.group_code
p
  strong User:
  = @paper.user_id
p
  strong Paper type code:
  = @paper.paper_type_code
p
  strong Limit time:
  = @paper.limit_time
p
  strong Question type:
  = @paper.question_type
p
  strong Is automatic:
  = @paper.is_automatic
p
  strong In use:
  = @paper.in_use

= link_to 'Edit', edit_paper_path(@paper)
'|
= link_to 'Back', papers_path