rts/config/routes.rb
Rts::Application.routes.draw do




  #get "/managers(.:format)" => "managers#index"
  #get "/api/managers/:hp" => "managers#show"
    #get "/managers(.:format)" => "managers#index"
  #put "/api/managers/:hp" => "managers#update"

  scope '/api' do

  resources :answers

  resources :paper_types, :id => /.*/

  resources :custom_groups

  resources :jobs

  resources :gifts

  resources :authorities

  resources :managers, :id => /.*/

  resources :customs

  resources :custom_answers

  resources :paper_histories

  resources :question_types

  resources :question_items

  resources :directives

  resources :papers

  resources :manager, :id => /.*/

  resources :groupinfos, :id => /.*/

  resources :shares

  #get "/manager/basicInfo" => 'manager#basicInfo'

    devise_for :users,
      :controllers => {
        omniauth_callbacks: "users/omniauth_callbacks",
        registrations: "users/registrations",
        sessions: "users/sessions"
      }

    devise_scope :user do
      post '/check/is_user' => 'users/users#is_user', as: 'is_user'
      post '/current_user' => 'users/sessions#get_current_user'
      
    end

  end


  get '/dashboard' => 'welcome#dashboard'
  root to: 'welcome#index'
end

rts/app/models/gift.rb
class Gift
  include Mongoid::Document
  #field :gift_no, type: Integer
  field :paper_id, type: Integer
  field :custom_id, type: String

  auto_increment :gift_no

  belongs_to :custom
  belongs_to :paper
end

rts/app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gift }
      else
        format.html { render action: 'new' }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:gift_no, :paper_id, :custom_id)
    end
end

rts/app/helpers/gifts_helper.rb
module GiftsHelper
end

rts/app/views/gifts/_form.html.slim
= form_for @gift do |f|
  - if @gift.errors.any?
    #error_explanation
      h2 = "#{pluralize(@gift.errors.count, "error")} prohibited this gift from being saved:"
      ul
        - @gift.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :gift_no
    = f.number_field :gift_no
  .field
    = f.label :paper_id
    = f.number_field :paper_id
  .field
    = f.label :custom_id
    = f.text_field :custom_id
  .actions = f.submit 'Save'

rts/app/views/gifts/edit.html.slim
h1 Editing gift

== render 'form'

= link_to 'Show', @gift
'|
= link_to 'Back', gifts_path

rts/app/views/gifts/index.html.slim
h1 Listing gifts

table
  tr
    th Gift no
    th Paper
    th Custom
    th
    th
    th

  - @gifts.each do |gift|
    tr
      td = gift.gift_no
      td = gift.paper_id
      td = gift.custom_id
      td = link_to 'Show', gift
      td = link_to 'Edit', edit_gift_path(gift)
      td = link_to 'Destroy', gift, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Gift', new_gift_path

rts/app/views/gifts/new.html.slim
h1 New gift

== render 'form'

= link_to 'Back', gifts_path

rts/app/views/gifts/show.html.slim
p#notice = notice

p
  strong Gift no:
  = @gift.gift_no
p
  strong Paper:
  = @gift.paper_id
p
  strong Custom:
  = @gift.custom_id

= link_to 'Edit', edit_gift_path(@gift)
'|
= link_to 'Back', gifts_path