rts/config/routes.rb
Rts::Application.routes.draw do




  #get "/managers(.:format)" => "managers#index"
  #get "/api/managers/:hp" => "managers#show"
    #get "/managers(.:format)" => "managers#index"
  #put "/api/managers/:hp" => "managers#update"

  scope '/api' do

  resources :answers

  resources :paper_types, :id => /.*/

  resources :custom_groups

  resources :jobs

  resources :gifts

  resources :authorities

  resources :managers, :id => /.*/

  resources :customs

  resources :custom_answers

  resources :paper_histories

  resources :question_types

  resources :question_items

  resources :directives

  resources :papers

  resources :manager, :id => /.*/

  resources :groupinfos, :id => /.*/

  resources :shares

  #get "/manager/basicInfo" => 'manager#basicInfo'

    devise_for :users,
      :controllers => {
        omniauth_callbacks: "users/omniauth_callbacks",
        registrations: "users/registrations",
        sessions: "users/sessions"
      }

    devise_scope :user do
      post '/check/is_user' => 'users/users#is_user', as: 'is_user'
      post '/current_user' => 'users/sessions#get_current_user'
      
    end

  end


  get '/dashboard' => 'welcome#dashboard'
  root to: 'welcome#index'
end

rts/app/models/paper_history.rb
class PaperHistory
  include Mongoid::Document
  field :user_id, type: String
  field :paper_id, type: Integer
  field :start_date, type: Date
  field :status, type: String

  field :groupinfo_code, type: String
  field :groupinfo_name, type: String
  field :paper_type_code, type: String
  field :paper_type_name, type: String

  belongs_to :paper
  belongs_to :manager
end

rts/app/controllers/paper_histories_controller.rb
class PaperHistoriesController < ApplicationController
  before_action :set_paper_history, only: [:show, :edit, :update, :destroy]

  # GET /paper_histories
  # GET /paper_histories.json
  def index
    @paper_histories = PaperHistory.all
  end

  # GET /paper_histories/1
  # GET /paper_histories/1.json
  def show
  end

  # GET /paper_histories/new
  def new
    @paper_history = PaperHistory.new
  end

  # GET /paper_histories/1/edit
  def edit
  end

  # POST /paper_histories
  # POST /paper_histories.json
  def create
    @paper_history = PaperHistory.new(paper_history_params)

    #respond_to do |format|
      if @paper_history.save
    #    format.html { redirect_to @paper_history, notice: 'Paper history was successfully created.' }
    #    format.json { render action: 'show', status: :created, location: @paper_history }
         render json: @paper_history
      else
    #    format.html { render action: 'new' }
    #    format.json { render json: @paper_history.errors, status: :unprocessable_entity }
         render json: paper_history.errors, status: :unprocessable_entity
      end
    #end
  end

  # PATCH/PUT /paper_histories/1
  # PATCH/PUT /paper_histories/1.json
  def update
    #respond_to do |format|
      if @paper_history.update(paper_history_params)
     #   format.html { redirect_to @paper_history, notice: 'Paper history was successfully updated.' }
     #   format.json { head :no_content }
         render json: @paper_history
      else
      #  format.html { render action: 'edit' }
      # format.json { render json: @paper_history.errors, status: :unprocessable_entity }
         render json: @paper_history.errors, status: :unprocessable_entity
      end
    #end
  end

  # DELETE /paper_histories/1
  # DELETE /paper_histories/1.json
  def destroy
    @paper_history.destroy
    render @paper_history
    #respond_to do |format|
    #  format.html { redirect_to paper_histories_url }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper_history
      @paper_history = PaperHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_history_params  
      params.require(:paper_history).permit(:user_id, :paper_id, :start_date, :status, :groupinfo_code, :groupinfo_name, :paper_type_code, :paper_type_name )
    end
end

rts/app/helpers/paper_histories_helper.rb
module PaperHistoriesHelper
end

rts/app/views/paper_histories/_form.html.slim
= form_for @paper_history do |f|
  - if @paper_history.errors.any?
    #error_explanation
      h2 = "#{pluralize(@paper_history.errors.count, "error")} prohibited this paper_history from being saved:"
      ul
        - @paper_history.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :paper_id
    = f.number_field :paper_id
  .field
    = f.label :start_date
    = f.date_select :start_date
  .field
    = f.label :status
    = f.text_field :status
  .actions = f.submit 'Save'

rts/app/views/paper_histories/edit.html.slim
h1 Editing paper_history

== render 'form'

= link_to 'Show', @paper_history
'|
= link_to 'Back', paper_histories_path

rts/app/views/paper_histories/index.html.slim
h1 Listing paper_histories

table
  tr
    th User
    th Paper
    th Start date
    th Status
    th
    th
    th

  - @paper_histories.each do |paper_history|
    tr
      td = paper_history.user_id
      td = paper_history.paper_id
      td = paper_history.start_date
      td = paper_history.status
      td = link_to 'Show', paper_history
      td = link_to 'Edit', edit_paper_history_path(paper_history)
      td = link_to 'Destroy', paper_history, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Paper history', new_paper_history_path

rts/app/views/paper_histories/new.html.slim
h1 New paper_history

== render 'form'

= link_to 'Back', paper_histories_path

rts/app/views/paper_histories/show.html.slim
p#notice = notice

p
  strong User:
  = @paper_history.user_id
p
  strong Paper:
  = @paper_history.paper_id
p
  strong Start date:
  = @paper_history.start_date
p
  strong Status:
  = @paper_history.status

= link_to 'Edit', edit_paper_history_path(@paper_history)
'|
= link_to 'Back', paper_histories_path