rts/config/routes.rb
Rts::Application.routes.draw do




  #get "/managers(.:format)" => "managers#index"
  #get "/api/managers/:hp" => "managers#show"
    #get "/managers(.:format)" => "managers#index"
  #put "/api/managers/:hp" => "managers#update"

  scope '/api' do

  resources :answers

  resources :paper_types, :id => /.*/

  resources :custom_groups

  resources :jobs

  resources :gifts

  resources :authorities

  resources :managers, :id => /.*/

  resources :customs

  resources :custom_answers

  resources :paper_histories

  resources :question_types

  resources :question_items

  resources :directives

  resources :papers

  resources :manager, :id => /.*/

  resources :groupinfos, :id => /.*/

  resources :shares

  #get "/manager/basicInfo" => 'manager#basicInfo'

    devise_for :users,
      :controllers => {
        omniauth_callbacks: "users/omniauth_callbacks",
        registrations: "users/registrations",
        sessions: "users/sessions"
      }

    devise_scope :user do
      post '/check/is_user' => 'users/users#is_user', as: 'is_user'
      post '/current_user' => 'users/sessions#get_current_user'
      
    end

  end


  get '/dashboard' => 'welcome#dashboard'
  root to: 'welcome#index'
end

rts/app/models/directive.rb
class Directive
  include Mongoid::Document
  field :paper_id, type: Integer
  #field :directive_no, type: Integer
  field :content, type: String
  field :q_type, type: String

  auto_increment :directive_no

  has_many :answer
  #has_many :questionitem
  #has_many :customanswer
  
  belongs_to :paper
  belongs_to :questiontype

end

rts/app/controllers/directives_controller.rb
class DirectivesController < ApplicationController
  before_action :set_directive, only: [:edit, :update, :destroy]
  #before_action :set_directive, except: [:index, :create]
  before_action :set_alldirective, only: [:show]

  # GET /directives
  # GET /directives.json
  def index
    @directives = Directive.all
  end

  # GET /directives/1
  # GET /directives/1.json
  def show
    render json: @directive
  end

  # GET /directives/new
  def new
    @directive = Directive.new
  end

  # GET /directives/1/edit
  def edit
  end

  # POST /directives
  # POST /directives.json
  def create
    @directive = Directive.new(directive_params)

    #respond_to do |format|
      if @directive.save
    #    format.html { redirect_to @directive, notice: 'Directive was successfully created.' }
    #    format.json { render action: 'show', status: :created, location: @directive }
         render json: @directive
      else
    #    format.html { render action: 'new' }
    #    format.json { render json: @directive.errors, status: :unprocessable_entity }
          render json: @directive.errors, status: :unprocessable_entity
      end
    #end
  end

  # PATCH/PUT /directives/1
  # PATCH/PUT /directives/1.json
  def update
    #respond_to do |format|
      if @directive.update(directive_params)
    #    format.html { redirect_to @directive, notice: 'Directive was successfully updated.' }
    #    format.json { head :no_content }
         render json: @directive
      else
    #    format.html { render action: 'edit' }
    #    format.json { render json: @directive.errors, status: :unprocessable_entity }
          render json: @directive.errors, status: :unprocessable_entity
      end
    #end
  end

  # DELETE /directives/1
  # DELETE /directives/1.json
  def destroy
    @directive.destroy

    head :no_content
  #  respond_to do |format|
  #    format.html { redirect_to directives_url }
  #    format.json { head :no_content }
  #  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directive
      @directive = Directive.find(params[:id])
    end

   def set_alldirective
       @directive = Directive.where(paper_id:params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directive_params
      params.require(:directive).permit(:paper_id, :directive_no, :content, :q_type)
    end
end

rts/app/helpers/directives_helper.rb
module DirectivesHelper
end

rts/app/views/directives/_form.html.slim
= form_for @directive do |f|
  - if @directive.errors.any?
    #error_explanation
      h2 = "#{pluralize(@directive.errors.count, "error")} prohibited this directive from being saved:"
      ul
        - @directive.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :paper_id
    = f.text_field :paper_id
  .field
    = f.label :directive_no
    = f.number_field :directive_no
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :q_type
    = f.text_field :q_type
  .actions = f.submit 'Save'

rts/app/views/directives/edit.html.slim
h1 Editing directive

== render 'form'

= link_to 'Show', @directive
'|
= link_to 'Back', directives_path

rts/app/views/directives/index.html.slim
h1 Listing directives

table
  tr
    th Paper
    th Directive no
    th Content
    th Q type
    th
    th
    th

  - @directives.each do |directive|
    tr
      td = directive.paper_id
      td = directive.directive_no
      td = directive.content
      td = directive.q_type
      td = link_to 'Show', directive
      td = link_to 'Edit', edit_directive_path(directive)
      td = link_to 'Destroy', directive, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Directive', new_directive_path

rts/app/views/directives/new.html.slim
h1 New directive

== render 'form'

= link_to 'Back', directives_path

rts/app/views/directives/show.html.slim
p#notice = notice

p
  strong Paper:
  = @directive.paper_id
p
  strong Directive no:
  = @directive.directive_no
p
  strong Content:
  = @directive.content
p
  strong Q type:
  = @directive.q_type

= link_to 'Edit', edit_directive_path(@directive)
'|
= link_to 'Back', directives_path